language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - yarn global add firebase-tools
  - yarn install
script:
  - yarn test
  - yarn build
before_deploy:
  - yarn build
branches:
  only:
    - master